### ISSUE TITLE
AttributeError: 'AllError' object has no attribute 'message'

### ISSUE THREAD

**Issue by jquast** [GreenSteam/pep257#151]
This follows up #142 -- using pep257 tool from master branch, a new error is revealed:

```
Traceback (most recent call last):
  File "/Users/docker/Code/telnetlib3/.tox/sa/lib/python3.4/site-packages/prospector/tools/pep257/__init__.py", line 42, in run
    code_file,
  File "/Users/docker/Code/telnetlib3/.tox/sa/lib/python3.4/site-packages/pep257.py", line 1319, in check_source
    module = parse(StringIO(source), filename)
  File "/Users/docker/Code/telnetlib3/.tox/sa/lib/python3.4/site-packages/pep257.py", line 265, in __call__
    return self.parse_module()
  File "/Users/docker/Code/telnetlib3/.tox/sa/lib/python3.4/site-packages/pep257.py", line 415, in parse_module
    children = list(self.parse_definitions(Module, all=True))
  File "/Users/docker/Code/telnetlib3/.tox/sa/lib/python3.4/site-packages/pep257.py", line 349, in parse_definitions
    self.parse_all()
  File "/Users/docker/Code/telnetlib3/.tox/sa/lib/python3.4/site-packages/pep257.py", line 399, in parse_all
    self.current.kind)
pep257.AllError: Unexpected token kind in  __all__: tk.NAME. That means pep257 cannot decide which definitions are public. Variable __all__ should be present at most once in each file, in form `__all__ = ('a_public_function', 'APublicClass', ...)`. More info on __all__: http://stackoverflow.com/q/44834/.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/docker/Code/telnetlib3/.tox/sa/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/Users/docker/Code/telnetlib3/.tox/sa/lib/python3.4/site-packages/prospector/run.py", line 143, in main
    prospector.execute()
  File "/Users/docker/Code/telnetlib3/.tox/sa/lib/python3.4/site-packages/prospector/run.py", line 52, in execute
    messages += tool.run(found_files)
  File "/Users/docker/Code/telnetlib3/.tox/sa/lib/python3.4/site-packages/prospector/tools/pep257/__init__.py", line 72, in run
    message=exc.message,
AttributeError: 'AllError' object has no attribute 'message'
```

**Comment by jquast** [comment]
will move to prospector project
